### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by andrie** [flightaware/mdsplib#9]
When I run `Make`, I get compilation errors that indicate variable names that conflict with the names of variables in `stdlib`.

I'm using `gcc` v8.3.0 on Windows

```
gcc -g -O2 -fPIC -c src/antoi.c -o src/antoi.o
gcc -g -O2 -fPIC -c src/charcmp.c -o src/charcmp.o
In file included from src/charcmp.c:25:
src/local.h:1096:11: error: conflicting types for 'itoa'
 MDSP_BOOL itoa(int, char *, int);
           ^~~~
In file included from src/local.h:55,
                 from src/charcmp.c:25:
C:/rtools40/mingw64/x86_64-w64-mingw32/include/stdlib.h:637:17: note: previous declaration of 'itoa' was here
   char *__cdecl itoa(int _Val,char *_DstBuf,int _Radix) __MINGW_ATTRIB_DEPRECATED_MSVC2005;
                 ^~~~
In file included from src/charcmp.c:25:
src/local.h:1179:5: error: conflicting types for 'strcmpi'
 int strcmpi(char *, char *);
     ^~~~~~~
In file included from src/local.h:56,
                 from src/charcmp.c:25:
C:/rtools40/mingw64/x86_64-w64-mingw32/include/string.h:109:15: note: previous declaration of 'strcmpi' was here
   int __cdecl strcmpi(const char *_Str1,const char *_Str2) __MINGW_ATTRIB_DEPRECATED_MSVC2005;
               ^~~~~~~
make: *** [Makefile:29: src/charcmp.o] Error 1

```

**Comment by snoe925** [comment]
We have merged multiple cleanups into master.  Can you pull and test these changes?
We are building for Windows on appveyor.  https://ci.appveyor.com/project/snoe925/mdsplib
We do not have a mingw build to test with. (It's possible on appveyor).

**Comment by andrie** [comment]
That's really helpful, thank you!

This newer version compiles without errors, and far fewer warnings than previously.

I still get some warnings about `stringop-overflow` (but I suspect you know about this already, since you hint about this in the Readme).

```
gcc -g -O2 -fPIC -c src/decode_metar_remark.c -o src/decode_metar_remark.o
src/decode_metar_remark.c: In function 'isRecentWX.isra.25':
src/decode_metar_remark.c:2271:19: warning: 'strncpy' specified bound depends on the length of the source argument [-Wstringop-overflow=]
                   strncpy(Mptr->ReWx[*NDEX].Recent_weather,
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                           phenom[i], (strlen(phenom[i])-1) );
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/decode_metar_remark.c:2272:39: note: length computed here
                           phenom[i], (strlen(phenom[i])-1) );
                                       ^~~~~~~~~~~~~~~~~
src/decode_metar_remark.c:2216:19: warning: 'strncpy' specified bound depends on the length of the source argument [-Wstringop-overflow=]
                   strncpy(Mptr->ReWx[*NDEX].Recent_weather,
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                              phenom[i], (strlen(phenom[i])-1) );
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/decode_metar_remark.c:2217:42: note: length computed here
                              phenom[i], (strlen(phenom[i])-1) );
                                          ^~~~~~~~~~~~~~~~~
src/decode_metar_remark.c:2370:19: warning: 'strncpy' specified bound depends on the length of the source argument [-Wstringop-overflow=]
                   strncpy( Mptr->ReWx[*NDEX].Recent_weather,
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                            phenom[i], (strlen(phenom[i])-1) );
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/decode_metar_remark.c:2371:40: note: length computed here
                            phenom[i], (strlen(phenom[i])-1) );
                                        ^~~~~~~~~~~~~~~~~
src/decode_metar_remark.c:2324:19: warning: 'strncpy' specified bound depends on the length of the source argument [-Wstringop-overflow=]
                   strncpy( Mptr->ReWx[*NDEX].Recent_weather,
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                            phenom[i], (strlen(phenom[i])-1) );
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/decode_metar_remark.c:2325:40: note: length computed here
                            phenom[i], (strlen(phenom[i])-1) );
                                        ^~~~~~~~~~~~~~~~~
```

**Comment by bovine** [comment]
I'm going to close this issue, since the original concerns about compile errors appear to have been addressed.

Concerns about potential buffer overflows and improper buffer limit checking would need to be addressed by a larger effort to make the entire codebase safer, including replacing all uses of strcat with strncat, and sprintf with snprintf, and passing around buffer sizes. We welcome separate pull requests on those improvements or any other fixes you can identify.

**Comment by andrie** [comment]
Thank you very much for your work!

I get a completely clean compile now, thanks to the changes you've made.
